//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

pub use super::correct_option::Entity as CorrectOption;
pub use super::details::Entity as Details;
pub use super::exam::Entity as Exam;
pub use super::options::Entity as Options;
pub use super::questions::Entity as Questions;
pub use super::sections::Entity as Sections;
