//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sections")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub details_id: i32,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::details::Entity",
        from = "Column::DetailsId",
        to = "super::details::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Details,
    #[sea_orm(has_many = "super::questions::Entity")]
    Questions,
}

impl Related<super::details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Details.def()
    }
}

impl Related<super::questions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Questions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
